# Site settin
title: Libdol | Libra | FR
description: La newsletter francophone du Libra, 1 fois/semaine
cover: https://i.ibb.co/bQMQQHH/fond3.png
logo:
favicon: /assets/images/favicon.png
baseurl: #the subpath of your site, e.g. /blog/ or / for root
url: "https://libdol.com" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: Nous contacter


permalink: /:title


# G oogle Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: A-Marc #github username
repo: libdol #github repository
branch: master #branch
relative_source: ../libdol/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url: https://libdol.com
source_url:  https://github.com/a-marc/libdol #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
