# Site settin
title: Libdol | Libra | FR
description: La newsletter francophone du Libra, 1 fois/semaine
cover: https://image.noelshack.com/fichiers/2019/32/2/1565107129-fond3.png
logo:
favicon: https://image.noelshack.com/fichiers/2019/31/4/1564664214-favicon.png
baseurl: # the subpath of your site, e.g. /blog/ or / for root
url: "https://polar-caverns-52525.herokuapp.com/" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# G oogle Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: A-Marc #github username
repo: libdol #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://polar-caverns-52525.herokuapp.com/
source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
